---
name: Package Test Publish

on: push

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

jobs:
  Package_For_PIP:
    uses: ./.github/workflows/Package.yaml

  Regression_Tests:
    needs:
      - Package_For_PIP
    uses: ./.github/workflows/Regression_Tests.yaml

  Regression_Tests_Agent:
    needs:
      - Package_For_PIP
    uses: ./.github/workflows/Regression_Tests_Agent.yaml

  Publish_Package:
    needs:
    - Package_For_PIP
    - Regression_Tests
    uses: ./.github/workflows/Publish.yaml
