---
name: Package test Publish

on: push

jobs:
  Package_For_PIP:
    uses: ./.github/workflows/Package.yaml

  Regression_Tests:
    needs:
      - Package_For_PIP
    uses: ./.github/workflows/Regression_Tests.yaml

  # Publish_Package:
  #   needs:
  #   - Package_For_PIP
  #   - Regression_Tests
  #   uses: ./.github/workflows/Package.yaml
