---
name: Regression Tests

on: push

jobs:
  Agent:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python: ['3.6', '3.7', '3.8', '3.9', '3.10']
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - run: pip install robotframework configparser requests robotframework psutil
      - name: Robot Framework
        run: robot --include ${{ matrix.platform }} Tests/Regression/Agent
  Manager:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python: ['3.7', '3.8', '3.9', '3.10']
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - run: pip install robotframework configparser requests HTTPServer pillow psutil matplotlib
      - name: Robot Framework
        run: robot --include ${{ matrix.platform }} Tests/Regression/Manager
  Reporter:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python: ['3.9', '3.10']
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - run: pip install -r Tests/Regression/Reporter/pip_requirements.txt
      - name: Robot Framework
        run: robot --include ${{ matrix.platform }} Tests/Regression/Reporter
