---
name: Regression Tests

on: push

jobs:
  Agent:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python: ['3.7', '3.8', '3.9', '3.10', '3.11']
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - run: pip install -r Tests/Regression/Agent/pip_requirements.txt
      - name: Robot Framework
        run: robot --include ${{ matrix.platform }} Tests/Regression/Agent
  Manager:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python: ['3.7', '3.8', '3.9', '3.10', '3.11']
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: "Ubuntu Installs"
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: |
          sudo apt install python3-tk python3-dev python3-xlib scrot fluxbox
          sudo apt list --installed
      - name: "Ubuntu Xvfb"
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: |
          export DISPLAY=:13.0
          Xvfb :13 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          # xauth with complain unless ~/.Xauthority exists
          touch ~/.Xauthority
          # To view a listing of the .Xauthority file, enter the following
          xauth list
          # fluxbox
          fluxbox &
      - run: pip install -r Tests/Regression/Manager/pip_requirements.txt
      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git config advice.addIgnoredFile false
      - name: create branch for test results
        run: git checkout -B Test-Result-${{ matrix.platform }}-${{ matrix.python }}
      - name: Robot Framework
        run: robot --include ${{ matrix.platform }} --outputdir Tests/Regression/Manager/Logs/${{ matrix.platform }}_${{ matrix.python }} Tests/Regression/Manager
        env:
          DISPLAY: :13.0
      - name: git commit
        if: always()
        run: |
          # Stage the file, commit and push
          echo "git add"
          git add Tests/Regression/Manager/Logs/${{ matrix.platform }}_${{ matrix.python }}/
          echo "git commit"
          git commit -m "Manager ${{ matrix.platform }} ${{ matrix.python }}"
      - name: Switch back to original branch
        if: always()
        run: |
          echo "git checkout ref_name: ${{ github.ref_name }}"
          git checkout -f ${{ github.ref_name }}
          echo "git pull"
          git pull --ff --autostash -f
      - name: Merge test results into original branch
        if: always()
        run: |
          echo "git merge"
          git merge --ff Test-Result-Manager-${{ matrix.platform }}-${{ matrix.python }}
          echo "git pull again"
          git pull --ff --autostash
          echo "git push"
          git push
  Reporter:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python: ['3.9', '3.10', '3.11']
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: "Ubuntu Installs"
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: |
          sudo apt install python3-tk python3-dev python3-xlib scrot fluxbox
          sudo apt list --installed
      - name: "Ubuntu Xvfb"
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: |
          export DISPLAY=:13.0
          Xvfb :13 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          # xauth with complain unless ~/.Xauthority exists
          touch ~/.Xauthority
          # To view a listing of the .Xauthority file, enter the following
          xauth list
          # fluxbox
          fluxbox &
      - run: pip install -r Tests/Regression/Reporter/pip_requirements.txt
      - name: Robot Framework
        run: robot --include ${{ matrix.platform }} --outputdir Tests/Regression/Reporter/Logs/${{ matrix.platform }}_${{ matrix.python }} Tests/Regression/Reporter
        env:
          DISPLAY: :13.0
      - name: git commit
        if: always()
        run: |
          # Stage the file, commit and push
          echo "git add"
          git add Tests/Regression/Reporter/Logs/${{ matrix.platform }}_${{ matrix.python }}/
          echo "git commit"
          git commit -m "Reporter ${{ matrix.platform }} ${{ matrix.python }}"
      - name: Switch back to original branch
        if: always()
        run: |
          echo "git checkout ref_name: ${{ github.ref_name }}"
          git checkout -f ${{ github.ref_name }}
          echo "git pull"
          git pull --ff --autostash -f
      - name: Merge test results into original branch
        if: always()
        run: |
          echo "git merge"
          git merge --ff Test-Result-Reporter-${{ matrix.platform }}-${{ matrix.python }}
          echo "git pull again"
          git pull --ff --autostash
          echo "git push"
          git push
