---
name: Regression Tests

on: push

jobs:
  Agent:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python: ['3.6', '3.7', '3.8', '3.9', '3.10']
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - run: pip install -r Tests/Regression/Agent/pip_requirements.txt
      - name: Robot Framework
        run: robot --include ${{ matrix.platform }} Tests/Regression/Agent
  Manager:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python: ['3.7', '3.8', '3.9', '3.10']
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - run: pip install -r Tests/Regression/Manager/pip_requirements.txt
      - name: Robot Framework
        run: robot --include ${{ matrix.platform }} --outputdir Tests/Regression/Manager/Logs/${{ matrix.platform }}_${{ matrix.python }} Tests/Regression/Manager
      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"        
      - name: git commit
        run: |
          # Stage the file, commit and push
          git add Tests/Regression/Manager/Logs/*
          git commit -m "${{ matrix.platform }} ${{ matrix.python }}"
          git pull --all --ff -r --autostash
          git push -f
  Reporter:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python: ['3.9', '3.10']
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - run: pip install -r Tests/Regression/Reporter/pip_requirements.txt
      - name: Robot Framework
        run: robot --include ${{ matrix.platform }} Tests/Regression/Reporter
