---
name: Super-Linter

on:
  push:
    paths-ignore:
      - '**.png'
      - '**.jpg'
  pull_request:
    types: [opened, reopened]

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: github/super-linter@v6
        env:
          DEFAULT_BRANCH: master
          FILTER_REGEX_EXCLUDE: (.*sh|.git/.*|.Doc/Images/.*|.Tests/.*/Logs/.*|.Tests/.*/testdata/.*)
          VALIDATE_PYTHON_BLACK: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_CSS: false
          VALIDATE_HTML: false
          VALIDATE_JSCPD: false
