---
name: Super-Linter

on:
  push:
    paths-ignore:
      - '**.png'
      - '**.jpg'
  pull_request:
    types: [opened, reopened]

permissions: read-all

jobs:
  super-lint:
    name: Lint code base
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout master
      #   uses: actions/checkout@v4
      #   with:
      #     ref: master

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display Branch Name
        run: echo "Current Branch: ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"

      - name: Run Super-Linter
        uses: super-linter/super-linter@v6
        env:
          DEFAULT_BRANCH: : ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          FILTER_REGEX_EXCLUDE: (.*sh|.git/.*|.Doc/Images/.*|.Tests/.*/Logs/.*|.Tests/.*/testdata/.*)
          VALIDATE_PYTHON_BLACK: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_CSS: false
          VALIDATE_HTML: false
          VALIDATE_JSCPD: false
