---
name: Deploy Website

on: workflow_call

jobs:
  Build-main-website:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create main Website
      run: |
        mkdir website
        echo '<!DOCTYPE html><html><body>' > website/index.html
        echo '<h1>Test Cases RF-Dashboard reports:</h1>' >> website/index.html
        echo '<ul>' >> website/index.html
        echo '<li><a href="dashboard/Agent/"> Agent </a></li>' >> website/index.html
        echo '<li><a href="dashboard/Manager/"> Manager </a></li>' >> website/index.html
        echo '<li><a href="dashboard/Reporter/"> Reporter </a></li>' >> website/index.html
        echo '</ul>' >> website/index.html
        echo '</body></html>' >> website/index.html

  Generate-reports:
    runs-on: ubuntu-latest
    needs: Build-main-website
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
      - name: Pip Update
        run: python -m pip install --upgrade pip
      - name: Install RF-Dashboard
        run: pip install robotframework-dashboard

      - name: Download Agent XML data artifact
        uses: actions/download-artifact@v4
        with:
          name: agent-XMLdata-ALL
          path: xml_data/Agent
      - run: ls -R xml_data/Agent
      - name: Build Agent Dashboard
        run: >
          robotdashboard
          -f xml_data/Agent
          -n website/dashboard/Agent/index.html

      # - name: Download Manager XML data artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: manager-XMLdata-ALL
      #     path: xml_data/Manager
      # - run: ls -R xml_data/Manager
      # - name: Build Manager Dashboard
      #   run: >
      #     robotdashboard
      #     -f xml_data/Manager
      #     -n website/dashboard/Manager/index.html

      # - name: Download Reporter XML data artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: reporter-XMLdata-ALL
      #     path: xml_data/Reporter
      # - run: ls -R xml_data/Reporter
      # - name: Build Reporter Dashboard
      #   run: >
      #     robotdashboard
      #     -f xml_data/Reporter
      #     -n website/dashboard/Reporter/index.html

      - name: Deploy website to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website
          keep_files: true
