---
name: Deploy Website

on: workflow_call

jobs:
  Build-website:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create main Website
        run: |
          mkdir -p website
          {
          echo '<!DOCTYPE html><html><body>'
          echo '<h1>Test Cases RF-Dashboard reports:</h1>'
          echo '<ul>'
          echo '<li><a href="dashboard/Agent/"> Agent </a></li>'
          echo '<li><a href="dashboard/Manager/"> Manager </a></li>'
          echo '<li><a href="dashboard/Reporter/"> Reporter </a></li>'
          echo '</ul>'
          echo '</body></html>'
          } > website/index.html

      - name: Setup Python
        uses: actions/setup-python@v5
      - name: Pip Update
        run: python -m pip install --upgrade pip
      - name: Install RF-Dashboard
        run: pip install robotframework-dashboard

      - name: Download Agent XML data artifact
        uses: actions/download-artifact@v4
        with:
          name: agent-XMLdata-ALL
          path: xml_data/Agent
      - run: ls -R xml_data/Agent
      - name: Build Agent Dashboard
        run: >
          robotdashboard
          -d xml_data/Agent/agent-dashboard.db
          -f xml_data/Agent
          -n website/dashboard/Agent/index.html
          -a True

      - name: Download Manager XML data artifact
        uses: actions/download-artifact@v4
        with:
          name: manager-XMLdata-ALL
          path: xml_data/Manager
      - run: ls -R xml_data/Manager
      - name: Build Manager Dashboard
        run: >
          robotdashboard
          -d xml_data/Manager/manager-dashboard.db
          -f xml_data/Manager
          -n website/dashboard/Manager/index.html
          -a True

      - name: Download Reporter XML data artifact
        uses: actions/download-artifact@v4
        with:
          name: reporter-XMLdata-ALL
          path: xml_data/Reporter
      - run: ls -R xml_data/Reporter
      - name: Build Reporter Dashboard
        run: >
          robotdashboard
          -d xml_data/Reporter/reporter-dashboard.db
          -f xml_data/Reporter
          -n website/dashboard/Reporter/index.html
          -a True

      - name: Deploy website to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website
          keep_files: true
